# Generated by Django 5.2.17 on 2026-09-08 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.system.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Текст сообщения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, default='', verbose_name='Содержание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_items', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('file', models.FileField(upload_to=apps.system.models.SystemDocument.doc_upload_to, verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_docs', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документация',
                'ordering': ['sort_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Наименование')),
                ('command', models.CharField(max_length=64, verbose_name='Команда')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='Параметры (JSON)')),
                ('run_mode', models.CharField(choices=[('manual', 'Только вручную'), ('scheduled', 'По расписанию')], default='manual', max_length=16, verbose_name='Режим запуска')),
                ('interval_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Интервал (минут)')),
                ('enabled', models.BooleanField(default=True, verbose_name='Активно')),
                ('last_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск')),
                ('last_finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее завершение')),
                ('last_result', models.CharField(blank=True, default='', max_length=16, verbose_name='Результат последнего запуска')),
                ('last_log', models.TextField(blank=True, default='', verbose_name='Лог последнего запуска')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задачи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_by', models.CharField(default='user', max_length=16, verbose_name='Инициатор')),
                ('started_at', models.DateTimeField(verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение')),
                ('result', models.CharField(blank=True, default='', max_length=16, verbose_name='Результат')),
                ('log', models.TextField(blank=True, default='', verbose_name='Лог')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='system.taskjob', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Запуск задания',
                'verbose_name_plural': 'Запуски заданий',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTableViewPref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_key', models.CharField(max_length=32, verbose_name='Таблица')),
                ('columns', models.JSONField(blank=True, default=list, verbose_name='Колонки (порядок)')),
                ('sorting', models.JSONField(blank=True, default=dict, verbose_name='Сортировка')),
                ('fixed_first', models.BooleanField(default=False, verbose_name='Фиксировать первую колонку')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_prefs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройка таблицы',
                'verbose_name_plural': 'Настройки таблиц',
                'constraints': [models.UniqueConstraint(fields=('user', 'table_key'), name='uniq_user_table_pref')],
            },
        ),
    ]
