# Generated by Django 5.2.17 on 2026-09-09 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.system.models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskjob',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='taskjob',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Низкий'), (1, 'Средний'), (2, 'Высокий')], default=0, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='taskjob',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('running', 'В работе'), ('completed', 'Завершена'), ('failed', 'Ошибка'), ('cancelled', 'Отменена')], default='created', max_length=16, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.system.models.TaskFile.task_upload_to, verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='system.taskjob', verbose_name='Задание')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл задачи',
                'verbose_name_plural': 'Файлы задач',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='system.taskjob', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Заметка к задаче',
                'verbose_name_plural': 'Заметки к задачам',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='system.taskjob', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Отчёт по задаче',
                'verbose_name_plural': 'Отчёты по задачам',
                'ordering': ['-created_at'],
            },
        ),
    ]
