# Generated by Django 5.2.17 on 2026-09-09 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_taskjob_assigned_to_taskjob_priority_taskjob_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemdocument',
            name='downloads_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Скачиваний'),
        ),
        migrations.AddField(
            model_name='systemdocument',
            name='file_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Размер (байт)'),
        ),
        migrations.AddField(
            model_name='systemdocument',
            name='file_type',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Тип файла'),
        ),
        migrations.AddField(
            model_name='systemdocument',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Код (авто)'),
        ),
        migrations.AddField(
            model_name='systemdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='systemdocument',
            name='version',
            field=models.CharField(default='1.0', max_length=16, verbose_name='Версия'),
        ),
        migrations.CreateModel(
            name='DocCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('icon', models.CharField(blank=True, default='', max_length=32, verbose_name='SVG-иконка')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='system.doccategory', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория документации',
                'verbose_name_plural': 'Категории документации',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='systemdocument',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs', to='system.doccategory', verbose_name='Категория'),
        ),
    ]
