# Generated by Django 5.2.17 on 2026-09-10 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.system.models
import apps.system.validators


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_systemdocument_downloads_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Код')),
                ('icon', models.CharField(blank=True, default='', max_length=32, verbose_name='SVG-иконка')),
            ],
            options={
                'verbose_name': 'Категория новостей',
                'verbose_name_plural': 'Категории новостей',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='newsitem',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.system.models.NewsItem.news_cover_upload_to, verbose_name='Обложка'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Закреплено сверху'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Код (авто)'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='summary',
            field=models.TextField(blank=True, default='', verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Просмотров'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='text',
            field=models.TextField(blank=True, default='', verbose_name='Содержание (HTML)'),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Диалоги',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Текст')),
                ('reactions', models.JSONField(blank=True, default=dict, verbose_name='Реакции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Изменено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_replies', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='system.messagereply', verbose_name='Ответ на')),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_replies', to=settings.AUTH_USER_MODEL, verbose_name='Прочитано')),
            ],
            options={
                'verbose_name': 'Сообщение диалога',
                'verbose_name_plural': 'Сообщения диалогов',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.system.models.MessageAttachment.attachment_upload_to, validators=[apps.system.validators.validate_document_file], verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='system.messagereply', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Вложение диалога',
                'verbose_name_plural': 'Вложения диалогов',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='Тема')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='system.conversation', verbose_name='Диалог')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_threads', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='messagereply',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='system.messagethread', verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='system.newscategory', verbose_name='Категория'),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
