# Generated by Django 5.2.17 on 2026-09-10 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_validate_taskfile_uploads'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='messagereply',
            index=models.Index(fields=['thread', '-created_at'], name='system_reply_latest_idx'),
        ),
        migrations.AddIndex(
            model_name='taskjob',
            index=models.Index(fields=['enabled', 'run_mode', 'status'], name='system_task_schedule_idx'),
        ),
    ]
