# Generated by Django 5.2.17 on 2026-09-10 19:15

from django.db import migrations, models

import apps.system.models
import apps.system.validators


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_messagereply_system_reply_latest_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.system.models.NewsItem.news_cover_upload_to, validators=[apps.system.validators.validate_image_file], verbose_name='Обложка'),
        ),
    ]
