# Generated by Django 5.2.17 on 2026-09-11 18:13

from django.db import migrations, models

import apps.system.models
import apps.system.validators


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0007_alter_newsitem_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messageattachment",
            name="file",
            field=models.FileField(
                upload_to=apps.system.models.MessageAttachment.attachment_upload_to,
                validators=[apps.system.validators.validate_attachment_file],
                verbose_name="Файл",
            ),
        ),
        migrations.AlterField(
            model_name="systemdocument",
            name="file",
            field=models.FileField(
                upload_to=apps.system.models.SystemDocument.doc_upload_to,
                validators=[apps.system.validators.validate_document_file],
                verbose_name="Файл",
            ),
        ),
        migrations.AlterField(
            model_name="taskfile",
            name="file",
            field=models.FileField(
                upload_to=apps.system.models.TaskFile.task_upload_to,
                validators=[apps.system.validators.validate_attachment_file],
                verbose_name="Файл",
            ),
        ),
    ]
