# Generated by Django 5.2.17 on 2026-09-11 18:53

from django.conf import settings
from django.db import migrations, models


def normalize_legacy_tasks(apps, schema_editor):
    TaskJob = apps.get_model("system", "TaskJob")

    for task in TaskJob.objects.exclude(command__in=("noop", "exchange_import")):
        original_command = task.command
        task.command = "noop"
        task.enabled = False
        task.status = "cancelled"
        task.last_log = (
            "Отключено миграцией: неизвестная команда "
            f"«{original_command}» заменена безопасной no-op."
        )
        task.save(update_fields=("command", "enabled", "status", "last_log"))

    TaskJob.objects.exclude(
        status__in=("created", "running", "completed", "failed", "cancelled")
    ).update(status="failed", enabled=False)
    TaskJob.objects.exclude(priority__in=(0, 1, 2)).update(priority=0)
    TaskJob.objects.filter(run_mode="manual").update(interval_minutes=None)
    TaskJob.objects.exclude(run_mode__in=("manual", "scheduled")).update(
        run_mode="manual",
        interval_minutes=None,
        status="cancelled",
        enabled=False,
    )
    TaskJob.objects.filter(run_mode="scheduled", interval_minutes__isnull=True).update(
        run_mode="manual",
        status="cancelled",
        enabled=False,
    )
    TaskJob.objects.filter(run_mode="scheduled", interval_minutes__lt=1).update(
        run_mode="manual",
        interval_minutes=None,
        status="cancelled",
        enabled=False,
    )
    TaskJob.objects.filter(status="running", last_started_at__isnull=True).update(
        status="failed",
        enabled=False,
        last_result="failed",
        last_log="Отключено миграцией: состояние запуска не имело времени начала.",
    )


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0008_alter_messageattachment_file_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(normalize_legacy_tasks, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="taskjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("command__in", ("noop", "exchange_import"))),
                name="system_task_command_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ("created", "running", "completed", "failed", "cancelled"))
                ),
                name="system_task_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskjob",
            constraint=models.CheckConstraint(
                condition=models.Q(("priority__in", (0, 1, 2))), name="system_task_priority_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="taskjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("interval_minutes__isnull", True), ("run_mode", "manual")),
                    models.Q(
                        ("interval_minutes__gte", 1),
                        ("interval_minutes__isnull", False),
                        ("run_mode", "scheduled"),
                    ),
                    _connector="OR",
                ),
                name="system_task_schedule_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="taskjob",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "running"), _negated=True),
                    ("last_started_at__isnull", False),
                    _connector="OR",
                ),
                name="system_task_running_started",
            ),
        ),
    ]
