# Generated by Django 5.2.17 on 2026-09-12 04:12

from django.conf import settings
from django.db import migrations, models


def normalize_enabled_cancelled_tasks(apps, schema_editor):
    TaskJob = apps.get_model("system", "TaskJob")
    TaskJob.objects.filter(enabled=True, status="cancelled").update(status="created")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('system', '0010_require_message_attachment_reply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(
            normalize_enabled_cancelled_tasks,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='taskjob',
            constraint=models.CheckConstraint(condition=models.Q(('enabled', False), models.Q(('status', 'cancelled'), _negated=True), _connector='OR'), name='system_task_enabled_not_cancelled'),
        ),
    ]
