# Generated by Django 5.2.17 on 2026-09-12 04:18

from django.db import migrations, models


def normalize_legacy_task_runs(apps, schema_editor):
    TaskRun = apps.get_model("system", "TaskRun")
    TaskRun.objects.exclude(triggered_by__in=("user", "auto")).update(
        triggered_by="legacy"
    )
    TaskRun.objects.filter(finished_at__isnull=True).exclude(result="").update(
        result=""
    )
    TaskRun.objects.filter(finished_at__isnull=False).exclude(
        result__in=("ok", "failed")
    ).update(result="failed")


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('system', '0011_enforce_task_enabled_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrun',
            name='result',
            field=models.CharField(blank=True, choices=[('ok', 'Успешно'), ('failed', 'Ошибка')], default='', max_length=16, verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='triggered_by',
            field=models.CharField(choices=[('user', 'Пользователь'), ('auto', 'Автоматически'), ('legacy', 'Исторический запуск')], default='user', max_length=16, verbose_name='Инициатор'),
        ),
        migrations.RunPython(normalize_legacy_task_runs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='taskrun',
            constraint=models.CheckConstraint(condition=models.Q(('triggered_by__in', ('user', 'auto', 'legacy'))), name='system_taskrun_trigger_valid'),
        ),
        migrations.AddConstraint(
            model_name='taskrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', True), ('result', '')), models.Q(('finished_at__isnull', False), ('result__in', ('ok', 'failed'))), _connector='OR'), name='system_taskrun_result_state'),
        ),
    ]
