# Generated by Django 5.2.17 on 2026-09-18 11:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def normalize_task_queue(apps, schema_editor):
    TaskJob = apps.get_model("system", "TaskJob")
    TaskRun = apps.get_model("system", "TaskRun")
    TaskJob.objects.filter(command="noop").update(command="database_health", params={})
    now = django.utils.timezone.now()
    for task_id in TaskRun.objects.filter(finished_at__isnull=True).values_list(
        "task_id", flat=True
    ).distinct():
        active = list(
            TaskRun.objects.filter(task_id=task_id, finished_at__isnull=True)
            .order_by("-started_at", "-pk")
            .values_list("pk", flat=True)
        )
        if len(active) > 1:
            TaskRun.objects.filter(pk__in=active[1:]).update(
                finished_at=now,
                result="failed",
                log="Исторический дублирующий незавершённый запуск закрыт при миграции очереди.",
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_eventlog_user'),
        ('system', '0013_enforce_task_last_result_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskrun',
            options={'ordering': ['-queued_at', '-pk'], 'verbose_name': 'Запуск задания', 'verbose_name_plural': 'Запуски заданий'},
        ),
        migrations.RemoveConstraint(
            model_name='taskjob',
            name='system_task_command_valid',
        ),
        migrations.RemoveConstraint(
            model_name='taskjob',
            name='system_task_status_valid',
        ),
        migrations.AddField(
            model_name='taskjob',
            name='max_retries',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Повторных попыток'),
        ),
        migrations.AddField(
            model_name='taskjob',
            name='retry_delay_seconds',
            field=models.PositiveIntegerField(default=60, verbose_name='Задержка повтора (секунд)'),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='attempt',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Попытка'),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='audit_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_run', to='core.eventlog', verbose_name='Событие аудита'),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='available_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Доступен для выполнения'),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Всего попыток'),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='queued_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Поставлен в очередь'),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_task_runs', to=settings.AUTH_USER_MODEL, verbose_name='Запросил'),
        ),
        migrations.AlterField(
            model_name='taskjob',
            name='status',
            field=models.CharField(choices=[('created', 'Создана'), ('queued', 'В очереди'), ('running', 'В работе'), ('completed', 'Завершена'), ('failed', 'Ошибка'), ('cancelled', 'Отменена')], default='created', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало'),
        ),
        migrations.RunPython(normalize_task_queue, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='taskjob',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('created', 'queued', 'running', 'completed', 'failed', 'cancelled'))), name='system_task_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='taskrun',
            constraint=models.CheckConstraint(condition=models.Q(('attempt__gte', 1), ('max_attempts__gte', 1), ('attempt__lte', models.F('max_attempts'))), name='system_taskrun_attempt_valid'),
        ),
        migrations.AddConstraint(
            model_name='taskrun',
            constraint=models.UniqueConstraint(condition=models.Q(('finished_at__isnull', True)), fields=('task',), name='system_one_active_taskrun'),
        ),
    ]
