# Generated by Django 5.2.17 on 2026-09-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(db_index=True, max_length=64, verbose_name='Модуль')),
                ('event_type', models.CharField(choices=[('login', 'Вход в систему'), ('login_failed', 'Неудачная аутентификация'), ('logout', 'Выход из системы'), ('create', 'Создание записи'), ('update', 'Изменение записи'), ('delete', 'Удаление записи'), ('import', 'Импорт данных'), ('export', 'Экспорт данных'), ('print', 'Печать'), ('send', 'Отправка/переадресация'), ('block', 'Блокировка учётной записи'), ('unblock', 'Разблокировка учётной записи'), ('task', 'Выполнение автоматизированного задания'), ('other', 'Прочее')], db_index=True, max_length=24, verbose_name='Тип события')),
                ('result', models.CharField(choices=[('ok', 'Успешно'), ('failed', 'Ошибка'), ('denied', 'Доступ запрещён')], default='ok', max_length=8, verbose_name='Результат')),
                ('target', models.CharField(blank=True, default='', max_length=200, verbose_name='Объект (атрибуты события)')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало события')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершение события')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (мс)')),
                ('detail', models.TextField(blank=True, default='', verbose_name='Детали')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'Журнал событий',
                'ordering': ['-id'],
            },
        ),
    ]
