# Generated by Django 5.2.17 on 2026-09-07 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['module', 'event_type'], name='core_eventl_module_5eaf22_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['user', '-id'], name='core_eventl_user_id_e832a1_idx'),
        ),
    ]
