# Generated by Django 5.2.17 on 2026-09-10 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_role_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['started_at'], name='core_event_started_idx'),
        ),
        migrations.AddIndex(
            model_name='eventlog',
            index=models.Index(fields=['result', '-id'], name='core_event_result_id_idx'),
        ),
    ]
