# Generated by Django 5.2.17 on 2026-09-11 20:17

from django.conf import settings
from django.db import migrations, models


def normalize_legacy_events(apps, schema_editor):
    EventLog = apps.get_model("core", "EventLog")
    EventLog.objects.filter(module="").update(module="unknown")
    EventLog.objects.exclude(
        event_type__in=(
            "login", "login_failed", "logout", "create", "update", "delete",
            "import", "export", "print", "send", "block", "unblock", "task", "other",
        )
    ).update(event_type="other", result="failed")
    EventLog.objects.exclude(result__in=("ok", "failed", "denied")).update(
        result="failed"
    )
    EventLog.objects.filter(finished_at__lt=models.F("started_at")).update(
        finished_at=models.F("started_at"), duration_ms=0
    )
    EventLog.objects.filter(finished_at__isnull=True).exclude(
        duration_ms__isnull=True
    ).update(duration_ms=None)
    EventLog.objects.filter(finished_at__isnull=False, duration_ms__isnull=True).update(
        duration_ms=0
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_consumedtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(normalize_legacy_events, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='eventlog',
            constraint=models.CheckConstraint(condition=models.Q(('module', ''), _negated=True), name='core_event_module_not_blank'),
        ),
        migrations.AddConstraint(
            model_name='eventlog',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ('login', 'login_failed', 'logout', 'create', 'update', 'delete', 'import', 'export', 'print', 'send', 'block', 'unblock', 'task', 'other'))), name='core_event_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='eventlog',
            constraint=models.CheckConstraint(condition=models.Q(('result__in', ('ok', 'failed', 'denied'))), name='core_event_result_valid'),
        ),
        migrations.AddConstraint(
            model_name='eventlog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('duration_ms__isnull', True), ('finished_at__isnull', True)), models.Q(('duration_ms__isnull', False), ('finished_at__isnull', False)), _connector='OR'), name='core_event_completion_pair'),
        ),
        migrations.AddConstraint(
            model_name='eventlog',
            constraint=models.CheckConstraint(condition=models.Q(('finished_at__isnull', True), ('finished_at__gte', models.F('started_at')), _connector='OR'), name='core_event_timeline_valid'),
        ),
    ]
