# Generated by Django 5.2.17 on 2026-09-11 23:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_eventlog_core_event_module_not_blank_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventlog',
            name='core_event_type_valid',
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.CharField(choices=[('login', 'Вход в систему'), ('login_failed', 'Неудачная аутентификация'), ('logout', 'Выход из системы'), ('create', 'Создание записи'), ('update', 'Изменение записи'), ('delete', 'Удаление записи'), ('import', 'Импорт данных'), ('export', 'Экспорт данных'), ('print', 'Печать'), ('view', 'Просмотр данных'), ('send', 'Отправка/переадресация'), ('block', 'Блокировка учётной записи'), ('unblock', 'Разблокировка учётной записи'), ('task', 'Выполнение автоматизированного задания'), ('other', 'Прочее')], db_index=True, max_length=24, verbose_name='Тип события'),
        ),
        migrations.AddConstraint(
            model_name='eventlog',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ('login', 'login_failed', 'logout', 'create', 'update', 'delete', 'import', 'export', 'print', 'view', 'send', 'block', 'unblock', 'task', 'other'))), name='core_event_type_valid'),
        ),
    ]
