# Generated by Django 5.2.17 on 2026-09-07 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='XmlFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=10, null=True, verbose_name='Версия файла')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Дата формирования файла')),
                ('year', models.CharField(max_length=4, verbose_name='Отчетный год')),
                ('month', models.CharField(max_length=2, verbose_name='Отчетный месяц')),
                ('day', models.CharField(max_length=2, verbose_name='День')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('smo', models.IntegerField(choices=[(81000, 'ТФОМС'), (81001, 'СОГАЗ - МЕД'), (81007, 'Капитал МС'), (81008, 'АльфаСтрахование - ОМС')], verbose_name='СМО')),
                ('filename', models.CharField(max_length=200, verbose_name='Имя файла')),
                ('real_filename', models.CharField(max_length=200, verbose_name='Имя файла на диске')),
            ],
            options={
                'verbose_name': 'Файл с обращениями',
                'verbose_name_plural': 'Файлы с обращениями',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Irp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_irp', models.CharField(max_length=36, unique=True, verbose_name='Уникальный номер обращения')),
                ('tf_id', models.UUIDField(blank=True, null=True, verbose_name='Идентификатор в ТФОМС')),
                ('irp_type', models.SmallIntegerField(choices=[(1, 'Консультация'), (2, 'Жалоба'), (3, 'Предложение'), (4, 'Заявление'), (5, 'вопросы, не относящиеся к сфере ОМС')], verbose_name='Вид обращения')),
                ('date_create', models.DateField(verbose_name='Дата поступления')),
                ('time_create', models.TimeField(blank=True, null=True, verbose_name='Время поступления')),
                ('way', models.SmallIntegerField(choices=[(1, 'Напрямую от заявителя'), (2, 'ФОМС'), (3, 'Иной федеральный орган исполнительной власти'), (4, 'Территориальный орган исполнительной власти'), (5, 'Иная организация'), (6, 'Контакт-центр Минздрава России')], verbose_name='Источник поступления')),
                ('way_n', models.CharField(blank=True, max_length=250, null=True, verbose_name='Организация-источник')),
                ('how', models.SmallIntegerField(choices=[(1, 'По телефону горячей линии'), (2, 'По сети Интернет'), (3, 'Личное письменное обращение'), (4, 'Личный прием (устное)'), (5, 'Почтовым сообщением')], verbose_name='Способ обращения')),
                ('theme_comment', models.CharField(blank=True, max_length=500, null=True, verbose_name='Комментарий к теме')),
                ('text', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Содержание обращения')),
                ('zh_d', models.CharField(blank=True, choices=[('1', 'Обоснованная'), ('1.1', 'Обоснованная, удовлетворенная в досудебном порядке'), ('1.2', 'Обоснованная, удовлетворенная в судебном порядке'), ('2', 'Необоснованная')], max_length=10, null=True, verbose_name='Сведения о жалобе')),
                ('otv_t', models.SmallIntegerField(choices=[(1, 'ТФОМС'), (2, 'СМО'), (3, 'ТФОМС (аутсорсинг)'), (4, 'СМО (аутсорсинг)'), (5, 'МО'), (6, 'ОИВ субъекта РФ'), (7, ' МО (аутсорсинг)'), (8, 'ОИВ субъекта РФ (аутсорсинг)')], verbose_name='Тип организации, ответственной за обращение')),
                ('otv_kon', models.IntegerField(choices=[(81000, 'ТФОМС'), (81001, 'СОГАЗ - МЕД'), (81007, 'Капитал МС'), (81008, 'АльфаСтрахование - ОМС')], verbose_name='Организация, ответственная за обращение')),
                ('line_one', models.SmallIntegerField(blank=True, choices=[(1, 'ОП1'), (2, 'ОП2'), (3, 'СП1'), (4, 'СП2'), (5, 'СП3'), (6, 'Администратор (или иной сотрудник ТФОМС)')], null=True, verbose_name='Линия принятия')),
                ('line_it', models.SmallIntegerField(blank=True, choices=[(1, 'ОП1'), (2, 'ОП2'), (3, 'СП1'), (4, 'СП2'), (5, 'СП3'), (6, 'Администратор (или иной сотрудник ТФОМС)')], null=True, verbose_name='Линия рассмотрения')),
                ('data_plan', models.DateField(verbose_name='Дата окончания срока рассмотрения')),
                ('date_close', models.DateField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('result', models.SmallIntegerField(blank=True, choices=[(1, 'Дана консультация'), (2, 'Рассмотрено обращение'), (3, 'Заявление удовлетворено'), (4, 'Заявление не удовлетворено'), (5, 'Рассмотрена жалоба'), (6, 'Звонок переадресован'), (7, 'Обращение переадресовано в другую организацию'), (8, 'Рассмотрено предложение')], null=True, verbose_name='Исход обращения')),
                ('z_f', models.CharField(blank=True, max_length=40, null=True, verbose_name='Фамилия')),
                ('z_i', models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя')),
                ('z_o', models.CharField(blank=True, max_length=40, null=True, verbose_name='Отчество')),
                ('z_dr', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('z_enp', models.CharField(blank=True, max_length=16, null=True, verbose_name='ЕНП')),
                ('z_smo', models.IntegerField(blank=True, choices=[(81000, 'ТФОМС'), (81001, 'СОГАЗ - МЕД'), (81007, 'Капитал МС'), (81008, 'АльфаСтрахование - ОМС')], null=True, verbose_name='Страховая принадлежность')),
                ('z_doctype', models.SmallIntegerField(blank=True, choices=[(1, 'Паспорт гражданина СССР'), (2, 'Загранпаспорт гражданина СССР'), (3, 'Свидетельство о рождении'), (4, 'Удостоверение личности офицера'), (5, 'Справка об освобождении из места лишения свободы'), (6, 'Паспорт Минморфлота'), (7, 'Военный билет'), (8, 'Дипломатический паспорт гражданина Российской Федерации'), (9, 'Иностранный паспорт'), (10, 'Свидетельство о регистрации ходатайства о признании иммигранта беженцем'), (11, 'Вид на жительство'), (12, 'Удостоверение беженца в Российской Федерации'), (13, 'Временное удостоверение личности гражданина Российской Федерации'), (14, 'Паспорт гражданина Российской Федерации'), (15, 'Заграничный паспорт гражданина Российской Федерации'), (16, 'Паспорт моряка'), (17, 'Военный билет офицера запаса'), (18, 'Иные документы, выдаваемые органами Министерства внутренних дел'), (21, 'Документ иностранного гражданина'), (22, 'Документ лица без гражданства'), (23, 'Разрешение на временное проживание'), (24, 'Свидетельство о рождении, выданное не в Российской Федерации'), (25, 'Свидетельство о предоставлении временного убежища на территории РФ'), (26, 'Удостоверение сотрудника Евразийской экономической комиссии'), (27, 'Копия жалобы о лишении статуса беженца'), (28, 'Иной документ,соотв. свидетельству о предоставлении убежища на территории РФ')], default=14, null=True, verbose_name='Тип документа, удостоверяющего личность')),
                ('z_docser', models.CharField(blank=True, max_length=10, null=True, verbose_name='Серия')),
                ('z_docnum', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер')),
                ('adr', models.CharField(blank=True, max_length=120, null=True, verbose_name='Адрес заявителя')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('e_mail', models.CharField(blank=True, max_length=200, null=True, verbose_name='E-mail заявителя')),
                ('in_f', models.CharField(blank=True, max_length=40, null=True, verbose_name='Фамилия')),
                ('in_i', models.CharField(blank=True, max_length=40, null=True, verbose_name='Имя')),
                ('in_o', models.CharField(blank=True, max_length=40, null=True, verbose_name='Отчество')),
                ('in_dr', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('in_enp', models.CharField(blank=True, max_length=16, null=True, verbose_name='ЕНП')),
                ('in_smo', models.IntegerField(blank=True, choices=[(81000, 'ТФОМС'), (81001, 'СОГАЗ - МЕД'), (81007, 'Капитал МС'), (81008, 'АльфаСтрахование - ОМС')], null=True, verbose_name='Страховая принадлежность')),
                ('in_doctype', models.SmallIntegerField(blank=True, choices=[(1, 'Паспорт гражданина СССР'), (2, 'Загранпаспорт гражданина СССР'), (3, 'Свидетельство о рождении'), (4, 'Удостоверение личности офицера'), (5, 'Справка об освобождении из места лишения свободы'), (6, 'Паспорт Минморфлота'), (7, 'Военный билет'), (8, 'Дипломатический паспорт гражданина Российской Федерации'), (9, 'Иностранный паспорт'), (10, 'Свидетельство о регистрации ходатайства о признании иммигранта беженцем'), (11, 'Вид на жительство'), (12, 'Удостоверение беженца в Российской Федерации'), (13, 'Временное удостоверение личности гражданина Российской Федерации'), (14, 'Паспорт гражданина Российской Федерации'), (15, 'Заграничный паспорт гражданина Российской Федерации'), (16, 'Паспорт моряка'), (17, 'Военный билет офицера запаса'), (18, 'Иные документы, выдаваемые органами Министерства внутренних дел'), (21, 'Документ иностранного гражданина'), (22, 'Документ лица без гражданства'), (23, 'Разрешение на временное проживание'), (24, 'Свидетельство о рождении, выданное не в Российской Федерации'), (25, 'Свидетельство о предоставлении временного убежища на территории РФ'), (26, 'Удостоверение сотрудника Евразийской экономической комиссии'), (27, 'Копия жалобы о лишении статуса беженца'), (28, 'Иной документ,соотв. свидетельству о предоставлении убежища на территории РФ')], null=True, verbose_name='Тип документа, удостоверяющего личность')),
                ('in_docser', models.CharField(blank=True, max_length=10, null=True, verbose_name='Серия')),
                ('in_docnum', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер')),
                ('pr_out', models.SmallIntegerField(blank=True, choices=[(1, 'обращение (запрос) направлено в МО субъекта РФ'), (2, 'обращение (запрос) направлено в ОИВ субъекта РФ'), (3, 'обращение (запрос) направлено в иную СМО субъекта РФ'), (4, 'обращение (запрос) направлено в организацию другого субъекта РФ')], null=True, verbose_name='Признак направления')),
                ('date_cross', models.DateField(blank=True, null=True, verbose_name='Дата направления')),
                ('time_cross', models.TimeField(blank=True, null=True, verbose_name='Время направления')),
                ('employee_it', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_it', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник, ответственный за обращение')),
                ('employee_one', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_1', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник, принявший обращение')),
            ],
            options={
                'verbose_name': 'Обращение',
                'verbose_name_plural': 'Обращения',
                'ordering': ['-date_create', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IrpHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=64, verbose_name='Поле')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Было')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Стало')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда изменено')),
                ('irp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='journal.irp')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кем изменено')),
            ],
            options={
                'verbose_name': 'Запись истории',
                'verbose_name_plural': 'История изменений',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='IrpTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=14, verbose_name='Код темы')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('version', models.IntegerField(default=1, verbose_name='Версия справочника')),
            ],
            options={
                'verbose_name': 'Тема обращения',
                'verbose_name_plural': 'Темы обращения',
                'ordering': ['-version', 'code_name'],
                'unique_together': {('code_name', 'version')},
            },
        ),
        migrations.AddField(
            model_name='irp',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='journal.irptheme', verbose_name='Тема обращения'),
        ),
        migrations.AddField(
            model_name='irp',
            name='input_file',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='journal.xmlfiles', verbose_name='Файл импорта'),
        ),
    ]
