# Generated by Django 5.2.17 on 2026-09-08 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IrpAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст ответа')),
                ('is_preliminary', models.BooleanField(default=True, verbose_name='Предварительный ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('irp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='journal.irp', verbose_name='Обращение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Кто подготовил')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IrpFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.journal.models.irp_file_path, verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='journal.irpanswer', verbose_name='Ответ')),
                ('irp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='journal.irp', verbose_name='Обращение')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-created_at'],
            },
        ),
    ]
