# Generated by Django 5.2.17 on 2026-09-10 19:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_irp_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='irp',
            index=models.Index(fields=['date_create', 'id'], name='journal_date_id_idx'),
        ),
        migrations.AddIndex(
            model_name='irp',
            index=models.Index(fields=['date_close', 'data_plan'], name='journal_close_plan_idx'),
        ),
    ]
