# Generated by Django 5.2.17 on 2026-09-11 18:13

from django.db import migrations, models

import apps.journal.models
import apps.system.validators


class Migration(migrations.Migration):
    dependencies = [
        ("journal", "0006_alter_irp_z_doctype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="irpfile",
            name="file",
            field=models.FileField(
                upload_to=apps.journal.models.irp_file_path,
                validators=[apps.system.validators.validate_attachment_file],
                verbose_name="Файл",
            ),
        ),
    ]
