# Generated by Django 5.2.17 on 2026-09-12 05:04

from django.db import migrations, models


def assert_legacy_xml_provenance_is_valid(apps, schema_editor):
    XmlFiles = apps.get_model("journal", "XmlFiles")
    valid = (
        models.Q(smo__in=(81000, 81001, 81007, 81008))
        & models.Q(year__regex=r"^[0-9]{4}$")
        & models.Q(month__regex=r"^(0[1-9]|1[0-2])$")
        & models.Q(day__regex=r"^(0[1-9]|[12][0-9]|3[01])$")
        & ~models.Q(filename="")
        & ~models.Q(real_filename="")
    )
    invalid_ids = list(
        XmlFiles.objects.exclude(valid).values_list("pk", flat=True)[:21]
    )
    if invalid_ids:
        rendered = ", ".join(str(pk) for pk in invalid_ids[:20])
        suffix = ", …" if len(invalid_ids) > 20 else ""
        raise RuntimeError(
            "Некорректные исторические XmlFiles требуют ручной проверки: "
            f"{rendered}{suffix}"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_irp_temporal_and_status_constraints'),
    ]

    operations = [
        migrations.RunPython(
            assert_legacy_xml_provenance_is_valid,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='xmlfiles',
            constraint=models.CheckConstraint(condition=models.Q(('smo__in', (81000, 81001, 81007, 81008))), name='xmlfiles_smo_valid'),
        ),
        migrations.AddConstraint(
            model_name='xmlfiles',
            constraint=models.CheckConstraint(condition=models.Q(('year__regex', '^[0-9]{4}$'), ('month__regex', '^(0[1-9]|1[0-2])$'), ('day__regex', '^(0[1-9]|[12][0-9]|3[01])$')), name='xmlfiles_date_parts_valid'),
        ),
        migrations.AddConstraint(
            model_name='xmlfiles',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('filename', ''), _negated=True), models.Q(('real_filename', ''), _negated=True)), name='xmlfiles_names_present'),
        ),
    ]
