"""Upgrade the confirmed journal.portal.tfoms v1 schema to the v2 baseline."""

from django.core.management.base import BaseCommand, CommandError
from django.db import DEFAULT_DB_ALIAS, connections, transaction

from .production_db_preflight import _columns, classify_schema

AUDIT_QUERIES = {
    "appeals with close date but no result": """
        SELECT count(*) FROM journal_irp
        WHERE date_close IS NOT NULL AND result IS NULL
    """,
    "appeals with result but no close date": """
        SELECT count(*) FROM journal_irp
        WHERE result IS NOT NULL AND date_close IS NULL
    """,
    "appeals with blank identifier": """
        SELECT count(*) FROM journal_irp WHERE n_irp ~ '^\\s*$'
    """,
    "appeals with complaint details on a non-complaint": """
        SELECT count(*) FROM journal_irp
        WHERE zh_d IS NOT NULL AND zh_d <> '' AND irp_type <> 2
    """,
    "appeals with redirect details but no redirect flag": """
        SELECT count(*) FROM journal_irp
        WHERE pr_out IS NULL AND (date_cross IS NOT NULL OR time_cross IS NOT NULL)
    """,
    "invalid XML provenance rows": """
        SELECT count(*) FROM journal_xmlfiles
        WHERE smo NOT IN (81000, 81001, 81007, 81008)
           OR year !~ '^[0-9]{4}$'
           OR month !~ '^(0[1-9]|1[0-2])$'
           OR day !~ '^(0[1-9]|[12][0-9]|3[01])$'
           OR filename = ''
           OR real_filename = ''
    """,
    "employees with unsupported organization": """
        SELECT count(*) FROM employee_employee
        WHERE org NOT IN (81000, 81001, 81007, 81008)
    """,
}


def audit_legacy_data(cursor) -> dict[str, int]:
    failures = {}
    for label, query in AUDIT_QUERIES.items():
        cursor.execute(query)
        count = cursor.fetchone()[0]
        if count:
            failures[label] = count
    return failures


def upgrade_legacy_schema(cursor) -> None:
    """Make v1 tables match the state expected after the colliding v2 initials."""
    cursor.execute(
        "LOCK TABLE employee_employee, journal_irptheme, journal_irp IN ACCESS EXCLUSIVE MODE"
    )
    cursor.execute(
        """
        ALTER TABLE employee_employee
            ADD COLUMN IF NOT EXISTS failed_attempts smallint NOT NULL DEFAULT 0,
            ADD COLUMN IF NOT EXISTS lock_until timestamp with time zone;
        ALTER TABLE employee_employee ALTER COLUMN job_title TYPE varchar(120);
        ALTER TABLE employee_employee DROP CONSTRAINT IF EXISTS employee_failed_attempts_nonnegative;
        ALTER TABLE employee_employee ADD CONSTRAINT employee_failed_attempts_nonnegative
            CHECK (failed_attempts >= 0);
        """
    )

    cursor.execute(
        """
        DO $$
        DECLARE foreign_key record;
        BEGIN
            FOR foreign_key IN
                SELECT conrelid::regclass AS table_name, conname
                FROM pg_constraint
                WHERE contype = 'f'
                  AND confrelid = 'journal_irptheme'::regclass
            LOOP
                EXECUTE format(
                    'ALTER TABLE %s DROP CONSTRAINT %I',
                    foreign_key.table_name,
                    foreign_key.conname
                );
            END LOOP;
        END $$;
        ALTER TABLE journal_irptheme DROP CONSTRAINT IF EXISTS journal_irptheme_pkey;
        ALTER TABLE journal_irptheme RENAME COLUMN code TO legacy_code;
        ALTER TABLE journal_irptheme ALTER COLUMN legacy_code DROP NOT NULL;
        ALTER TABLE journal_irptheme
            ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY;
        ALTER TABLE journal_irptheme ALTER COLUMN id SET NOT NULL;
        ALTER TABLE journal_irptheme ADD CONSTRAINT journal_irptheme_pkey PRIMARY KEY (id);
        ALTER TABLE journal_irptheme ADD CONSTRAINT journal_irptheme_legacy_code_key
            UNIQUE (legacy_code);

        ALTER TABLE journal_irp ADD COLUMN theme_id_v2 bigint;
        UPDATE journal_irp AS irp
        SET theme_id_v2 = theme.id
        FROM journal_irptheme AS theme
        WHERE theme.legacy_code = irp.theme_id;
        """
    )
    cursor.execute("SELECT count(*) FROM journal_irp WHERE theme_id_v2 IS NULL")
    missing_themes = cursor.fetchone()[0]
    if missing_themes:
        raise CommandError(
            f"Legacy upgrade aborted: {missing_themes} appeals have no matching theme."
        )
    cursor.execute(
        """
        ALTER TABLE journal_irp DROP COLUMN theme_id;
        ALTER TABLE journal_irp RENAME COLUMN theme_id_v2 TO theme_id;
        ALTER TABLE journal_irp ALTER COLUMN theme_id SET NOT NULL;
        ALTER TABLE journal_irp ADD CONSTRAINT journal_irp_theme_id_v2_fk
            FOREIGN KEY (theme_id) REFERENCES journal_irptheme(id)
            DEFERRABLE INITIALLY DEFERRED;
        CREATE INDEX journal_irp_theme_id_v2_idx ON journal_irp(theme_id);

        CREATE TABLE IF NOT EXISTS journal_irphistory (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            field_name varchar(64) NOT NULL,
            old_value text,
            new_value text,
            changed_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
            irp_id integer NOT NULL REFERENCES journal_irp(id) ON DELETE CASCADE
                DEFERRABLE INITIALLY DEFERRED,
            user_id integer REFERENCES employee_employee(id) ON DELETE SET NULL
                DEFERRABLE INITIALLY DEFERRED
        );
        CREATE INDEX IF NOT EXISTS journal_irphistory_irp_id_idx
            ON journal_irphistory(irp_id);
        CREATE INDEX IF NOT EXISTS journal_irphistory_user_id_idx
            ON journal_irphistory(user_id);
        """
    )


class Command(BaseCommand):
    help = "Upgrade a confirmed v1 database before applying v2 Django migrations."

    def add_arguments(self, parser):
        parser.add_argument("--database", default=DEFAULT_DB_ALIAS)
        parser.add_argument("--confirm", required=True)

    def handle(self, *args, **options):
        connection = connections[options["database"]]
        if options["confirm"] != "upgrade-journal-v1-in-place":
            raise CommandError(
                "Refusing legacy upgrade without --confirm upgrade-journal-v1-in-place."
            )
        if connection.vendor != "postgresql":
            raise CommandError("Legacy upgrade requires PostgreSQL.")

        with transaction.atomic(using=options["database"]), connection.cursor() as cursor:
            cursor.execute(
                "SELECT pg_advisory_xact_lock(hashtext(%s))",
                ["ofoms-ejournal-legacy-upgrade-v1"],
            )
            tables = set(connection.introspection.table_names(cursor))
            theme_columns = (
                _columns(cursor, "journal_irptheme") if "journal_irptheme" in tables else {}
            )
            schema_kind = classify_schema(tables, theme_columns)
            if schema_kind == "current":
                self.stdout.write("Legacy upgrade skipped: schema is already v2.")
                return
            if schema_kind != "legacy":
                raise CommandError(f"Refusing legacy upgrade for schema={schema_kind}.")
            cursor.execute(
                """
                    SELECT app, name FROM django_migrations
                    WHERE (app, name) IN (
                        ('contenttypes', '0001_initial'),
                        ('auth', '0001_initial'),
                        ('employee', '0001_initial'),
                        ('journal', '0001_initial')
                    )
                    """
            )
            migration_markers = set(cursor.fetchall())
            required_markers = {
                ("contenttypes", "0001_initial"),
                ("auth", "0001_initial"),
                ("employee", "0001_initial"),
                ("journal", "0001_initial"),
            }
            if migration_markers != required_markers:
                missing = sorted(required_markers - migration_markers)
                raise CommandError(
                    "Legacy migration history is incomplete; refusing to infer it. "
                    f"Missing: {missing}"
                )
            failures = audit_legacy_data(cursor)
            if failures:
                details = "; ".join(f"{label}: {count}" for label, count in failures.items())
                raise CommandError(f"Legacy data audit failed: {details}")
            upgrade_legacy_schema(cursor)

        self.stdout.write(
            self.style.SUCCESS(
                "Legacy v1 baseline upgraded to v2; run production_db_preflight and migrate."
            )
        )
