# Generated by Django 5.2.17 on 2026-09-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='org',
            field=models.IntegerField(choices=[(81000, 'ТФОМС'), (81001, 'СОГАЗ - МЕД'), (81007, 'Капитал МС'), (81008, 'АльфаСтрахование - ОМС')], db_index=True, verbose_name='Организация'),
        ),
    ]
