# Generated by Django 5.2.17 on 2026-09-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.IntegerField(choices=[(81000, 'ТФОМС'), (81001, 'СОГАЗ - МЕД'), (81007, 'Капитал МС'), (81008, 'АльфаСтрахование - ОМС')], verbose_name='Организация')),
                ('kind', models.CharField(choices=[('irp', 'Обращения (G1*)'), ('users', 'Сотрудники (users*)'), ('excel', 'Excel')], max_length=10, verbose_name='Тип')),
                ('filename', models.CharField(max_length=200, verbose_name='Имя файла')),
                ('status', models.CharField(choices=[('ok', 'Обработан без ошибок'), ('error', 'Обработан с ошибками')], max_length=6, verbose_name='Статус')),
                ('rows', models.PositiveIntegerField(default=0, verbose_name='Записей обработано')),
                ('flcp', models.TextField(blank=True, verbose_name='Протокол FLCP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Когда')),
            ],
            options={
                'verbose_name': 'Загрузка файла',
                'verbose_name_plural': 'Обмен данными (загрузки)',
                'ordering': ['-created_at'],
            },
        ),
    ]
