# Generated by Django 5.2.17 on 2026-09-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='importlog',
            index=models.Index(fields=['org', '-created_at'], name='exchange_org_created_idx'),
        ),
    ]
