# Generated by Django 5.2.17 on 2026-09-11 20:11

from django.db import migrations, models


def normalize_legacy_import_logs(apps, schema_editor):
    ImportLog = apps.get_model("exchange", "ImportLog")
    ImportLog.objects.exclude(org__in=(81000, 81001, 81007, 81008)).update(org=81000)
    ImportLog.objects.exclude(status__in=("ok", "error")).update(status="error")
    for item in ImportLog.objects.exclude(kind__in=("irp", "users", "excel")).only(
        "pk", "filename"
    ):
        filename = item.filename.lower()
        if filename.endswith(".xlsx"):
            kind = "excel"
        elif filename.startswith("users"):
            kind = "users"
        else:
            kind = "irp"
        ImportLog.objects.filter(pk=item.pk).update(kind=kind, status="error")


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_importlog_exchange_org_created_idx'),
    ]

    operations = [
        migrations.RunPython(normalize_legacy_import_logs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='importlog',
            constraint=models.CheckConstraint(condition=models.Q(('org__in', (81000, 81001, 81007, 81008))), name='exchange_import_org_valid'),
        ),
        migrations.AddConstraint(
            model_name='importlog',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ('irp', 'users', 'excel'))), name='exchange_import_kind_valid'),
        ),
        migrations.AddConstraint(
            model_name='importlog',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('ok', 'error'))), name='exchange_import_status_valid'),
        ),
    ]
